#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 ThreadX Shell Project
#
# Emit a C++ byte array + size for a TFLite model, for the tflm NN backend
# (Epic owhinata/stm32f746g-disco#80 P3 M2, owhinata/stm32f746g-disco#88).  Run at
# BUILD time by a custom command in cmake/tflite-micro.cmake (issue #130) to turn
# the pinned, sha256-verified BlazeFace .tflite (never committed) into a
# compilable translation unit inside the `tflm` static lib.
#
# We roll our own generator (rather than tflite-micro's generate_cc_arrays.py)
# for two reasons: (1) a FIXED symbol name decoupled from the input filename, so
# nn_tflm.cc can #include a stable header regardless of which .tflite is fed;
# (2) no numpy/Pillow dependency.  The array is alignas(16) to satisfy TFLM's
# flatbuffer alignment requirement (tflite::GetModel expects a 16-byte-aligned
# buffer).
#
#   gen_model_array.py <input.tflite> <out.cc> <out.h> <symbol> [--sha256 <hex>]
#
# [!] --sha256 RE-VERIFIES THE PIN AT USE (issue #130).  The fetch verified the
# file when it published it, but the array is generated from whatever is at that
# path NOW; with --sha256 the exact bytes emitted are hashed first and a mismatch
# fails with no output left behind.  Given but empty or malformed is a failure,
# not "no check".  Only the override path omits the option -- an override is a
# deliberately different model and is not hash-checked.
#
# Emits, for symbol `g_blazeface_model_data`:
#   out.h : extern const unsigned char  g_blazeface_model_data[];
#           extern const unsigned int   g_blazeface_model_data_size;
#   out.cc: alignas(16) const unsigned char g_blazeface_model_data[] = { ... };
#           const unsigned int g_blazeface_model_data_size = <N>;

import hashlib
import os
import re
import sys


def fail(msg, *stale):
    sys.stderr.write("gen_model_array: %s\n" % msg)
    # Leave nothing a later step could mistake for a generated array.
    for path in stale:
        try:
            os.remove(path)
        except OSError:
            pass
    return 1


def write_atomic(path, text):
    tmp = path + ".tmp"
    with open(tmp, "w") as f:
        f.write(text)
    os.replace(tmp, path)


def main():
    args = sys.argv[1:]
    want = None
    bad = None
    if "--sha256" in args:
        k = args.index("--sha256")
        if k + 1 >= len(args):
            bad = "--sha256 needs a value"
            del args[k:]
        else:
            want = args[k + 1]
            del args[k:k + 2]
            if not re.fullmatch(r"[0-9a-f]{64}", want):
                bad = ("--sha256 must be 64 lowercase hex digits, got %r -- an "
                       "empty expected hash is a failure, not 'no check'" % want)
    if len(args) != 4:
        sys.stderr.write(
            "usage: gen_model_array.py <input.tflite> <out.cc> <out.h> <symbol>"
            " [--sha256 <hex>]\n")
        return 1
    in_path, cc_path, h_path, symbol = args
    if bad:
        return fail(bad, cc_path, h_path)

    with open(in_path, "rb") as f:
        blob = f.read()
    if not blob:
        return fail("empty model file: %s" % in_path, cc_path, h_path)
    if want is not None:
        got = hashlib.sha256(blob).hexdigest()
        if got != want:
            return fail("%s is not the pinned content (%d B)\n  want: %s\n  got:  %s\n"
                        "  The file changed after the fetch verified it.  Delete it "
                        "and rebuild to fetch it again."
                        % (in_path, len(blob), want, got), cc_path, h_path)

    os.makedirs(os.path.dirname(cc_path) or ".", exist_ok=True)
    os.makedirs(os.path.dirname(h_path) or ".", exist_ok=True)
    hdr_name = os.path.basename(h_path)

    h = []
    h.append("/* Auto-generated by cmake/gen_model_array.py -- do not edit. */\n")
    h.append("#ifndef TFLM_MODEL_ARRAY_%s_H\n" % symbol.upper())
    h.append("#define TFLM_MODEL_ARRAY_%s_H\n\n" % symbol.upper())
    h.append("extern const unsigned char %s[];\n" % symbol)
    h.append("extern const unsigned int  %s_size;\n\n" % symbol)
    h.append("#endif\n")

    cc = []
    cc.append("/* Auto-generated by cmake/gen_model_array.py -- do not edit. */\n")
    cc.append('#include "%s"\n\n' % hdr_name)
    cc.append("alignas(16) const unsigned char %s[] = {\n" % symbol)
    # 16 bytes per line keeps the file readable and diffs sane.
    for i in range(0, len(blob), 16):
        row = blob[i:i + 16]
        cc.append("  " + ",".join("0x%02x" % b for b in row) + ",\n")
    cc.append("};\n")
    cc.append("const unsigned int %s_size = %du;\n" % (symbol, len(blob)))

    write_atomic(h_path, "".join(h))
    write_atomic(cc_path, "".join(cc))
    return 0


if __name__ == "__main__":
    sys.exit(main())
