# SPDX-License-Identifier: MIT
# Copyright (c) 2026 ThreadX Shell Project
#
# The audit target behind cmake/check_no_mutable_storage.py (issue #97).
#
# svc/blazeface.c is one decoder for three boards, and that only works because it
# owns no mutable storage: each board passes in its own candidate scratch, so the
# scratch keeps that board's placement and that board's residency gate keeps
# naming a symbol the board owns.  This compiles the shared file once more, on its
# own, and refuses any allocated writable section in the result.
#
# [!] IT MUST BE THE BOARD'S OWN COMPILE, or the gate is answering about a
# different object than the one that ships.  Two things were got wrong first and
# are the reason this lives in a function rather than three times in three
# board.cmake files:
#
#   1. INHERITING INCLUDES AND DEFINITIONS IS NOT ENOUGH.  The architecture flags
#      (-mcpu, -mthumb, -mfpu, -mfloat-abi, -mcmse) come from the board's
#      INTERFACE library, not from CMAKE_C_FLAGS, so a target that only copied
#      INCLUDE_DIRECTORIES and COMPILE_DEFINITIONS compiled for the compiler's
#      DEFAULT machine.  Linking the interface library is what makes the audit the
#      board's compile.  Measured before the fix: the audit's whole flag list was
#      "-O0 -fno-lto -fno-common".
#   2. A PER-SOURCE PROPERTY FOLLOWS THE SOURCE, NOT THE TARGET.  Grove sets -O3
#      on this file with set_source_files_properties(... TARGET_DIRECTORY ...),
#      and the audit target lives in that same directory -- so the -O3 landed on
#      the audit too, AFTER its own -O0, and won.  The audit compiled a source
#      file of its own that #includes the shared one instead, which the property
#      does not name.
#
# The audit deliberately overrides optimisation, LTO and common: it is an AUDIT
# compile that inherits the board's real definitions, includes and architecture,
# not a second copy of the build's own compile.  Say it that way in comments --
# claiming it IS the build's compile would be the same class of mistake.

function(add_decoder_storage_gate)
    cmake_parse_arguments(DSG "" "NAME;SOURCE;IFACE;CONSUMER" "" ${ARGN})
    if(NOT DSG_NAME OR NOT DSG_SOURCE OR NOT DSG_IFACE)
        message(FATAL_ERROR
            "add_decoder_storage_gate: NAME, SOURCE and IFACE are all required")
    endif()
    if(NOT EXISTS "${DSG_SOURCE}")
        message(FATAL_ERROR
            "add_decoder_storage_gate: no such source:\n  ${DSG_SOURCE}")
    endif()

    # The wrapper.  Compiling the shared file THROUGH an #include gives an object
    # with identical contents under a name no per-source property mentions.
    set(_wrap "${CMAKE_CURRENT_BINARY_DIR}/${DSG_NAME}_audit.c")
    file(WRITE "${_wrap}"
"/* Generated by cmake/decoder_storage_gate.cmake -- do not edit.\n"
" *\n"
" * Compiles the shared decoder as its own translation unit so that\n"
" * check_no_mutable_storage.py can be asked about it directly.  It is included\n"
" * rather than listed as a source because a per-source COMPILE_OPTIONS property\n"
" * follows the source path into every target in the directory, and this audit\n"
" * needs its own optimisation level.\n"
" */\n"
"#include \"${DSG_SOURCE}\"\n")

    add_library(${DSG_NAME} OBJECT EXCLUDE_FROM_ALL "${_wrap}")
    # The board's real compile: architecture, includes and definitions together.
    target_link_libraries(${DSG_NAME} PRIVATE ${DSG_IFACE})
    # ...and anything the consuming target adds on top of the interface, so a
    # board-specific include or define is not lost.
    if(DSG_CONSUMER)
        target_include_directories(${DSG_NAME} PRIVATE
            $<TARGET_PROPERTY:${DSG_CONSUMER},INCLUDE_DIRECTORIES>)
        target_compile_definitions(${DSG_NAME} PRIVATE
            $<TARGET_PROPERTY:${DSG_CONSUMER},COMPILE_DEFINITIONS>)
    endif()
    # The audit's own overrides, last so they win.
    target_compile_options(${DSG_NAME} PRIVATE -O0 -fno-lto -fno-common)

    add_custom_target(${DSG_NAME}_check
        COMMAND "${Python3_EXECUTABLE}"
                "${CMAKE_SOURCE_DIR}/cmake/check_no_mutable_storage.py"
                --objdump "${CMAKE_OBJDUMP}" --nm "${CMAKE_NM}"
                --label "${DSG_SOURCE} (${BOARD})"
                $<TARGET_OBJECTS:${DSG_NAME}>
        COMMENT "check the shared decoder owns no mutable storage"
        COMMAND_EXPAND_LISTS VERBATIM)
    add_dependencies(${DSG_NAME}_check ${DSG_NAME})
endfunction()
